### ISSUE TITLE
Sql Injection scanning hasn't been fixed

### ISSUE THREAD

**Issue by Merujan99** [v3n0m-Scanner/V3n0M-Scanner#16]
Traceback (most recent call last):
  File "v3n0m.py", line 748, in <module>
    fmenu()
  File "v3n0m.py", line 641, in fmenu
    fscan()
  File "v3n0m.py", line 543, in fscan
    vulnscan()
  File "v3n0m.py", line 572, in vulnscan
    injtest()
  File "v3n0m.py", line 312, in injtest
    sliced = usearch[x * i:(x + 1) * i]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by NovaCygni** [comment]
Duplicated Issue, Closing as literally about to add the int() to it now. I will reupload in about 8 hours as I have to go to work for 6 hours :walking:
