### ISSUE TITLE
Kali Rolling

### ISSUE THREAD

**Issue by jteslaxxx** [v3n0m-Scanner/V3n0M-Scanner#44]
Have problems running it on Kali, have all dependencies satisfied!
Here is output:
root@kali:~/V3n0M-Scanner# pip3 install dnspython3 aiohttp httplib2 socksipy-branch requests url
Requirement already satisfied (use --upgrade to upgrade): dnspython3 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): aiohttp in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): httplib2 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): socksipy-branch in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): url in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): multidict<2,>=1.2.2 in /usr/local/lib/python3.5/dist-packages (from aiohttp)
Requirement already satisfied (use --upgrade to upgrade): chardet in /usr/lib/python3/dist-packages (from aiohttp)
Requirement already satisfied (use --upgrade to upgrade): publicsuffix in /usr/local/lib/python3.5/dist-packages (from url)
when i run install --upgrade command, it upgrades all packages, everything seems fine! When I run scanner:
|------ PYTHON PROBLEM DETECTED! Recovery Menu Enabled -----| 
|--- You are advised to run either or both steps below   ---| 
|--- Recovery Menu is in early testing stage please let me know if you have any problems with it.   ---| 
[1] Run Pip3 and Auto-Update Python3 modules to latest versions, Requires Sudo or Root
[2] Run Pip3 and Auto-Install all the required v3n0m modules, Requires Sudo  or Root
[3] Exit
It starts, but when i give it target and parametres it crashes: Traceback (most recent call last):
  File "v3n0m.py", line 1159, in <module>
    fmenu()
  File "v3n0m.py", line 981, in fmenu
    fscan()
  File "v3n0m.py", line 637, in fscan
    usearch = loop.run_until_complete(search(pages_pulled_as_one))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "v3n0m.py", line 879, in search
    timestart = datetime.now()
NameError: name 'datetime' is not defined

**Comment by kattstof** [comment]
run option1 in the scanner, post any errors. also , try to run v3n0m even if you get errors with option1 could be a false pos. happened to me. im away from home atm so i cant really dig into it it could be a problem with the latest commit so if all else fails download the v3n0m 4.0.5 commit then use option one then upgrade v3n0m to 4.0.6

**Comment by NovaCygni** [comment]
use pip3 and check to  see you have time and datetime, I might add additional checks for Kali users as I keep getting people with basic modules missing :/ Im just about to go to work so I wont be able to the 4.0.6a Update till tomorrow morning.

**Comment by NovaCygni** [comment]
hotfix added: newbuild release number format:
Build release 407 includes the import fix for datetime in the Recovery Menu.
Ive not had a chance to test it yet so feedback would be appreciated.

**Comment by jteslaxxx** [comment]
All good and fine! I followed steps you mentioned above, passed both options 1 and 2 and now all good and fine! Thanks and Cheers
