### ISSUE TITLE
ValueError: expected parenthesized list

### ISSUE THREAD

**Issue by ju4npabl0** [v3n0m-Scanner/V3n0M-Scanner#47]
Hello!

I was trying to run `python3 setup.py` but I got these errors. Any idea how to fix them?

Thanks!

```
root@kali:~/V3n0M-Scanner# python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    packages=['v3n0m'], requires=['aiohttp', 'httplib2', 'socksipy-branch', 'requests', 'dns', 'url', 'bs4']
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.4/distutils/dist.py", line 252, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python3.4/distutils/dist.py", line 1209, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python3.4/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-branch'
root@kali:~/V3n0M-Scanner# pip3 install aiohttp httplib2 socksipy-branch requests dnspython url bs4 --upgrade
Requirement already up-to-date: aiohttp in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: httplib2 in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: socksipy-branch in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: requests in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: dnspython in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: url in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: bs4 in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: chardet in /usr/lib/python3/dist-packages (from aiohttp)
Requirement already up-to-date: multidict<2,>=1.2.2 in /usr/local/lib/python3.4/dist-packages (from aiohttp)
Requirement already up-to-date: publicsuffix in /usr/local/lib/python3.4/dist-packages (from url)
Requirement already up-to-date: beautifulsoup4 in /usr/local/lib/python3.4/dist-packages (from bs4)
root@kali:~/V3n0M-Scanner#
```

**Comment by NovaCygni** [comment]
Upgrade your Python from 3.4 to 3.5 ;)

**Comment by ju4npabl0** [comment]
Hello Nova!

I did `apt-get upgrade` and `apt-get dist-upgrade` but it is still not working properly.

```
root@kali:~/V3n0M-Scanner# python3 --version
Python 3.5.2+
root@kali:~/V3n0M-Scanner# python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    packages=['v3n0m'], requires=['aiohttp', 'httplib2', 'socksipy-branch', 'requests', 'dns', 'url', 'bs4']
  File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.5/distutils/dist.py", line 253, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/usr/lib/python3.5/distutils/dist.py", line 1208, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/usr/lib/python3.5/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-branch'
root@kali:~/V3n0M-Scanner# pip3 install dnspython3 aiohttp httplib2 socksipy-branch requests url --upgrade
Requirement already up-to-date: dnspython3 in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: aiohttp in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: httplib2 in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: socksipy-branch in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: requests in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: url in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: multidict<2,>=1.2.2 in /usr/local/lib/python3.5/dist-packages (from aiohttp)
Requirement already up-to-date: chardet in /usr/lib/python3/dist-packages (from aiohttp)
Requirement already up-to-date: publicsuffix in /usr/local/lib/python3.5/dist-packages (from url)
root@kali:~/V3n0M-Scanner#
```

**Comment by NovaCygni** [comment]
"Should" be fixed, was a problem with the way it was reading socksipy-branch, as the " - " in its name was being read as a Operand instead of just part of the name, ive changed the setup.py to use "Install_Requires" which supports PyPI naming instead of the "Requires" that was being used before.  Ill leave thread open and let you close it if its working fine for you.

**Comment by ju4npabl0** [comment]
Hello Nova!

Thanks! Issue is now resolved.

Cheers!
