### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by jteslaxxx** [v3n0m-Scanner/V3n0M-Scanner#50]
So on Kali Linux Rolling 2016.2 getting following error:
Traceback (most recent call last):
  File "v3n0m.py", line 33, in <module>
    import bs4
ImportError: No module named 'bs4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v3n0m.py", line 41, in <module>
    logo()
  File "v3n0m.py", line 12, in logo
    print(R + "\n|----------------------------------------------------------------|")

python3 --version
Python 3.5.2+

**Comment by jteslaxxx** [comment]
upated now all fine

**Comment by d4op** [comment]
Nice
